name: Lint

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-pr:
    runs-on: ubuntu-latest
    steps:
      # v6.1.1. https://github.com/amannn/action-semantic-pull-request/tree/v6.1.1
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
